# Generated by Django 2.2.5 on 2019-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20191028_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(help_text='침실 갯수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(help_text='침대 갯수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='묵을 게스트 수'),
        ),
    ]
